version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: always
    networks:
      - docker-network

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always
    networks:
      - docker-network

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wp-volume:/var/www/
    networks:
      - docker-network

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/rahmed/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/rahmed/data/mariadb

networks:
  docker-network:
    driver: bridge
